[package]
name = "alww-task-18"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.2.0"
encoding_rs = "0.8.32"
encoding_rs_io = "0.1.7"
serde = { version = "1.0.152", features = ["derive"] }
